### ISSUE TITLE
解压失败是何解？

### ISSUE THREAD

**Issue by memeDev** [overtrue/latest-laravel#19]
gzip: stdin: unexpected end of file
laravel/.git/objects/pack/pack-d8067b82e3a80fe860c51c66fec86556490481e2.pack
tar: 归档文件中异常的 EOF
tar: 归档文件中异常的 EOF
tar: Error is not recoverable: exiting now

**Comment by overtrue** [comment]
我看一下

**Comment by overtrue** [comment]
@memeDev 我试过了没问题啊，你删除重新下载试试
