### ISSUE TITLE
求4.2的包啊

### ISSUE THREAD

**Issue by gantoo** [overtrue/latest-laravel#20]
好像只有最新5.0的?
新手还是4.2资料多些 
希望有4.2的包

**Comment by overtrue** [comment]
从https://github.com/laravel/laravel/archive/v4.2.11.zip下载，然后`composer install`

**Comment by gantoo** [comment]
谢谢 我github还不大会用

**Comment by overtrue** [comment]
@gantoo 希望快速掌握基本使用，因为这是目前招聘的基本要求
